### ISSUE TITLE
🐛 Only part of the window is transparent if window is resized

### ISSUE THREAD

**Issue by y-u-s-u-f** [SenpaiHunters/Clakr#1]
### Bug Description

If you make the window bigger, only the original part will stay transparent.

### Steps To Reproduce

1. Open Clakr
2. Make the window bigger

### Expected Behavior

The whole window should be transparent.

### Actual Behavior

Only the original part is transparent

### Screenshots

![CleanShot 2024-04-09 at 17 33 53@2x](https://github.com/SenpaiHunters/Clakr/assets/67281394/adc3747d-108f-4e7f-b4b5-ef7785866029)

### MacOS Version

Sonoma 14.4.1

### Clakr Version

1.1

### Additional Context

By the way, you can't see/copy the version number from the about page.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by SenpaiHunters** [comment]
I know this issue, I'm trying to find an easy way of locking the size of the window to a fixed rate. However, whatever i do needs to support all the way from 12-14, for now, i recommend just changing the size back manually to its intended width, and i will update this in the next version(s) for better window support! When i find a better window method, i will update and or send it here.

**Comment by SenpaiHunters** [comment]
[clakr.app.zip](https://github.com/SenpaiHunters/Clakr/files/14926565/clakr.app.zip)
Here is an updated version that prevents it from being resized, @y-u-s-u-f .
