### ISSUE TITLE
🐛 Clakr Opens Settings when I do ⌘, in any app

### ISSUE THREAD

**Issue by y-u-s-u-f** [SenpaiHunters/Clakr#2]
### Bug Description

Basically if I have Clakr opened, but another app (eg arc) and I do ⌘, it still opens Clakr settings.

### Steps To Reproduce

1. Open Clakr
2. Open another app
3. Focus on the other app
4. Click ⌘,

### Expected Behavior

It only opens the settings window if Clakr is focused

### Actual Behavior

It opens the settings window even if Clakr is not focused.

### Screenshots

https://github.com/SenpaiHunters/Clakr/assets/67281394/543fe75d-a856-400e-bce5-fc34ea2dd734

### MacOS Version

14.4.1

### Clakr Version

Version 1.1

### Additional Context

Btw don't ask why I'm using FireFox 😭

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by SenpaiHunters** [comment]
Yep, thanks for this i fixed this issue as well. Will be posted on the next release.
