### ISSUE TITLE
✨ Add Version Number to About Section

### ISSUE THREAD

**Issue by y-u-s-u-f** [SenpaiHunters/Clakr#3]
### Feature Request Description

Basically add the version number and a button to copy it in the about section.

### Screenshots

![CleanShot 2024-04-10 at 15 01 07@2x](https://github.com/SenpaiHunters/Clakr/assets/67281394/953daafc-f978-48c2-b968-47ee26cb30b6)
![CleanShot 2024-04-10 at 15 01 56@2x](https://github.com/SenpaiHunters/Clakr/assets/67281394/8b009591-1473-4f30-aade-b9d1a16ad757)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by SenpaiHunters** [comment]
Ah, ok so there are two about sections. The macOS defaults in the menu bar under Clakr, then about you can copy it from here. Here is the about settings, but i may add it here, and don't mind the spelling mistake i fixed this in a recent version

**Comment by SenpaiHunters** [comment]
This is now added in version 1.1 (431) which can be found here -  https://github.com/SenpaiHunters/Clakr/releases/tag/1.1_(431)
